name: Windows Installer

on: push

jobs:

  build:
    permissions:
      contents: write
    strategy:
      matrix:
        configuration: [Release]
        os: [windows-latest]
        dotnetver: [8.x]

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{matrix.dotnetver}}
    - name: Install NSIS
      working-directory: frontend/MediaTekDocuments
      run: curl -Lo nsis.exe 'https://downloads.sourceforge.net/project/nsis/NSIS%203/3.08/nsis-3.08-setup.exe' && ./nsis.exe /S

    - name: Compile solution
      working-directory: frontend/MediaTekDocuments
      run: dotnet build -c ${{matrix.configuration}}
      
    - name: Download GTK dlls
      working-directory: frontend/MediaTekDocuments
      run: curl -LO https://raw.githubusercontent.com/GtkSharp/Dependencies/master/gtk-3.24.24.zip && mkdir gtk && unzip gtk-3.24.24.zip -d gtk

    - name: Build Installer
      working-directory: frontend/MediaTekDocuments
      run: makensis installer.nsi

    - name: Release
      uses: softprops/action-gh-release@v1 # apparently the official action for making a GH release is deprecated
      if: startsWith(github.ref, 'refs/tags/') # only for tags
      with:
        files: frontend/MediaTekDocuments/mediatek-installer.exe